### ISSUE TITLE
resize window?

### ISSUE THREAD

**Issue by seathasky** [progrium/topframe#15]
Possible to resize the overlay?

**Comment by progrium** [comment]
It's software, anything is possible. Do we want that? Do you have a reason?

**Comment by seathasky** [comment]
Hey thanks for responding! So I play a game called Final Fantasy 14, on mac/linux and there is combat tracker (ACT) https://advancedcombattracker.com/ that can utilize websockets to create dps windows for users on other platiforms (Mac / Linux) who cant utilize the native Windows plugin overlays due to Wine incompatibility with CEF (more so on Mac's jerry rigged wine atm) a DPS is generally very small window needed and not a full screen thing. 

Example: 
From: https://github.com/hibiyasleep/kagerou  

![kagerou-1](https://user-images.githubusercontent.com/17598024/134335250-ad63a530-a5c6-4891-bc1e-11ee136e03e5.png)
Atm, you're software is the only thing I can use (on Mac) other than a web browser that will redirect to websocket needed to show the dps meter. At the moment, using the rediected in the index.html works fine but it also fills the entire screen and takes ownership so that nothing else is useable.  :) These are my reasons, also maybe being able to use multiple instances of top frame would be dope too. 
But if this is too much trouble, for any of this,  honestly, shoot me down. I'm extremely familar with rejection when it comes to asking for stuff like this, Being a needle in a haystack mac/hackintosh gamer asking all these devs to accommodate me has been something i've had to accept

**Comment by seathasky** [comment]
any follow up on this?

**Comment by progrium** [comment]
Ideally the transparent background would be passthrough so you can just make elements the size you want. It's unlikely we'll add support for resizing the window.
